name: Lint & build
on: [push]
jobs:
  lint:
    name: Code linting
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16.x]
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pnpm-install

      - uses: actions/cache@v3
        id: restore-dependencies
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-dependencies-
            ${{ runner.os }}-

      - name: Run ESLint
        run: pnpm lint
          -o eslint-report.txt

      - uses: actions/upload-artifact@v3
        with:
          name: lint-test-report
          path: eslint-report.txt

  build-and-push-to-azure:
    name: build and push to Azure
    runs-on: ubuntu-20.04
    needs: lint
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3

      # - name: Login via Azure CLI
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Docker Registry Login
      #   uses: azure/docker-login@v1
      #   with:
      #     login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
      #     username: ${{ secrets.REGISTRY_USERNAME }}
      #     password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push image
        run: docker build . -t ${GITHUB_REPOSITORY}:${{ github.sha }}
      # run: |
        # docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/${GITHUB_REPOSITORY}:${{ github.sha }}
        # docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${GITHUB_REPOSITORY}:${{ github.sha }}

      # - name: 'Deploy to Azure Container Instances'
      #   uses: 'azure/aci-deploy@v1'
      #   with:
      #     resource-group: ${{ secrets.RESOURCE_GROUP }}
      #     dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
      #     image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/${GITHUB_REPOSITORY}:${{ github.sha }}
      #     registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
      #     registry-username: ${{ secrets.REGISTRY_USERNAME }}
      #     registry-password: ${{ secrets.REGISTRY_PASSWORD }}
      #     name: ${GITHUB_REPOSITORY}
      #     location: 'central us'
      #     ports: 3000
